apiVersion: v1
kind: Service
metadata:
  labels:
    app: configserver
  name: configserver
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8888
  selector:
    app: configserver
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver-deployment
spec:
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
        - name: configserver
          image: springcloud/configserver
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
              valueFrom:
                secretKeyRef:
                  name: configserver-secret
                  key: git-url
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL
              valueFrom:
                secretKeyRef:
                  name: configserver-secret
                  key: git-default-label
          readinessProbe:
            httpGet:
              port: 8888
              path: /actuator/health/readiness
          livenessProbe:
            httpGet:
              port: 8888
              path: /actuator/health/liveness
          ports:
            - containerPort: 8888
---
apiVersion: v1
data:
  git-default-label: cHJvZA==
  git-url: aHR0cHM6Ly9naXRodWIuY29tL3RzYWxtLXBpdm90YWwvc3ByaW5nLWNsb3VkLWRlbW8tY29uZmlnLXNlcnZlci1jb25maWd1cmF0aW9uLmdpdA==
kind: Secret
metadata:
  name: configserver-secret
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: configserver-binding-compatible
type: Opaque
stringData:
  type: config
  uri: http://configserver
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  name: configserver-binding-compatible
spec:
  ref:
    apiVersion: v1
    kind: Secret
    name: configserver-binding-compatible