apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: shipping-service
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: worker
  name: shipping-service
  namespace: sc-architecture
spec:
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
  params:
  - name: testing_pipeline_params
    value:
      source-sub-path: shipping-service
  serviceClaims:
  - name: rmq
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ClassClaim
      name: rmq-1
  - name: config-server
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: configserver-1
  - name: observability
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: zipkin-1
  source:
    git:
      ref:
        branch: main
      url: https://github.com/timosalm/spring-cloud-demo-tap.git
    subPath: shipping-service